name: Code Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的git历史用于检查变更
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install code quality checker
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/yourusername/code_quality_checker.git
          
      - name: Check code quality
        run: |
          # 如果是PR，只检查变更的文件
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            code-quality-check . --changed-only --report quality-report.txt
          else
            code-quality-check . --report quality-report.txt
          fi
          
      - name: Upload quality report
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-report
          path: quality-report.txt 